---
# This playbook deploys the whole application stack in this site.

- name: Central
  hosts: all
  remote_user: root

  roles:
    - common
    - central

- name: Poller
  hosts: all
  remote_user: root

  roles:
    - common
    - poller

- name: Db
  hosts: all
  remote_user: root

  roles:
    - common
    - db
