---
# This playbook contains common plays that will be run on all nodes.

- name: Install Selinux Management
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
    - libsemanage-python

- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: ensure SELinux is turned off
  action: command /usr/sbin/setenforce 0

# FIXME
#- name: Disable iptables
#  action: service name=iptables state=stopped enabled=false

- name: Install ntp
  yum: name=ntp state=present

- name: Set ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root
  notify:
    - restart ntpd

- name: Ensure that ntpd is running
  service: name=ntpd state=started enabled=yes

- name: Install snmpd
  yum: name=net-snmp state=present

- name: Set snmpd configuration
  template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf owner=root group=root
  notify:
    - restart snmpd

- name: Ensure that snmpd is running
  service: name=snmpd state=started enabled=yes

- name: Set CES repo.
  template: src=ces-standard.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Import CES GPG key.
  template: src=RPM-GPG-KEY-CES dest=/etc/pki/rpm-gpg/ owner=root group=root mode=0644
